## ------------------------------------
## PREPROD environment configuration
## ------------------------------------

## CkAppAlpha
api.ck-app-alpha.base-url=https://jsonplaceholder.typicode.com
api.ck-app-alpha.content-type=JSON
api.ck-app-alpha.timeout.connect=10000
api.ck-app-alpha.timeout.read=20000
api.ck-app-alpha.auth.type=none
api.ck-app-alpha.auth.token=
api.ck-app-alpha.logging=false

## CkAppBeta
api.ck-app-beta.base-url=https://fake-json-api.mock.beeceptor.com
api.ck-app-beta.content-type=JSON
api.ck-app-beta.timeout.connect=10000
api.ck-app-beta.timeout.read=20000
api.ck-app-beta.auth.type=none
api.ck-app-beta.auth.token=
api.ck-app-beta.logging=false
